services:
  frontend:
    image: anguspllg/note:latest
    container_name: note_frontend
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      NODE_ENV: production
      HOST: '0.0.0.0'
      ORIGIN: 'http://localhost:3000' # Change with your public IP/domain name. Ex : https://note.domain.com
      PORT: 3000
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    restart: always
    container_name: note_db
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/database.sql
